package com.epam.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
//@DynamoDBTable(tableName = "books")
public class Book {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
//	@DynamoDBHashKey
//	@DynamoDBAutoGeneratedKey
	private int bookId;
//	@DynamoDBAttribute
	private String name;
//	@DynamoDBAttribute
	private String publisher;
//	@DynamoDBAttribute
	private String author;
	
	public Book(String name, String publisher, String author) {
		super();
		this.name = name;
		this.publisher = publisher;
		this.author = author;
	}

}
