version: "3.8"
services:
  book-service:
    image : "book-service"
    restart: always
    ports:
      - 8002:8080
    depends_on:
      - mysqldb
#    environment:
#      MYSQL_HOST: mysqldb
#      MYSQL_PORT: 3306
#      MYSQL_USER: root
#      MYSQL_PASSWORD: epam

  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: epam
      MYSQL_DATABASE: books
      MYSQL_ROOT_PASSWORD: epam
