cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    credentials:
      access-key: AKIAUR3U2XTKO7LRC7H4
      secret-key: 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

    end-point:
      uri: https://sqs.us-east-2.amazonaws.com/313240763604/book-service


